[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ns"
version = "0.2.4"
description = "Novus power products configuration tool"
authors = [
    {name = "jaowens14", email = "jaowens14@protonmail.com"}
]
license = {text = "MIT"}
requires-python = ">=3.11, <3.13"
dependencies = [
    "aiofiles",
    "aiohappyeyeballs",
    "aiohttp",
    "aiosignal",
    "annotated-doc",
    "annotated-types",
    "anyio",
    "attrs",
    "beautifulsoup4",
    "bidict",
    "bs4",
    "certifi",
    "charset-normalizer",
    "click",
    "dbus-next",
    "docutils",
    "fastapi",
    "frozenlist",
    "h11",
    "httpcore",
    "httptools",
    "httpx",
    "idna",
    "ifaddr",
    "itsdangerous",
    "jinja2",
    "markdown2",
    "markupsafe",
    "multidict",
    "narwhals",
    "nicegui",
    "numpy",
    "orjson",
    "packaging",
    "pam",
    "pandas",
    "plotly",
    "propcache",
    "pydantic",
    "pydantic-core",
    "pygments",
    "python-dateutil",
    "python-dotenv",
    "python-engineio",
    "python-multipart",
    "python-pam",
    "python-socketio",
    "pyinstaller",
    "pyyaml",
    "requests",
    "simple-websocket",
    "six",
    "soupsieve",
    "typing-inspection",
    "typing-extensions",
    "urllib3",
    "uvicorn",
    "uvloop",
    "watchfiles",
    "websockets",
    "wheel2deb",
    "wsproto",
    "yarl",
]

[project.scripts]
ns = "ns.ui.main:main"

[tool.setuptools.packages.find]
where = ["src"]